services:
  redis:
    image: redis:7-alpine
    networks:
      - node-net

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - node-net

networks:
  node-net:
    driver: bridge